### ISSUE TITLE
Trimming plugins.

### ISSUE THREAD

**Issue by gustavnikolaj** [sunesimonsen/eslint-config-pretty-standard#10]
I got tired of seeing complaints about the missing peer dependencies in my projects :-) We have a peer dep on 4 plugins: react, promise, flowtype and standard - but only rules from the first two are actually referenced in the rules section of the configuration. I sent a PR for removing the two unused plugins in the configuration. #9 

I want to axe the other two aswell - but they are actually used, so I thought I'd try to bring it up instead :-) So that leaves to two questions:

1. [eslint-plugin-promise](https://github.com/xjamundx/eslint-plugin-promise) is providing only 1 used rule: `promise/param-names`. [It is poorly documented](https://github.com/xjamundx/eslint-plugin-promise/blob/master/docs/rules/param-names.md) but it seems to just force you to name the args to the `Promise`-constructors callback resolve and reject. ([source](https://github.com/xjamundx/eslint-plugin-promise/blob/master/rules/param-names.js#L22-L37)). Is that enough to warrant keeping it around? :-)
2. Would you be open to split up the react specific parts into a eslint-config-pretty-standard-react and keep this config completely clean?

That I should just stop caring and get over my self is an acceptable answer. I'm happy to do the required work if you want to pursue this.

**Comment by sunesimonsen** [comment]
This should be fixed when the PR was merged.
