### ISSUE TITLE
Simplify and extend

### ISSUE THREAD

**Issue by KidkArolis** [sunesimonsen/eslint-config-pretty-standard#13]
Now that eslint-config-prettier explicitly turns style rules off, it's possible to combine standard rules and prettier rules without explicitly listing all the rules. Like this:

```js
{
   "extends": ["standard", "standard-jsx", "prettier"],
   "plugins": ["prettier"],
   "rules": {
     "prettier/prettier": "error"
   }
}
```
(https://github.com/KidkArolis/pretty-standard/blob/master/eslintrc.json)

Plus, adding the prettier plugin means you can run `eslint --fix`.

Would you be open to update this package to use the above config? Or is there some other special rules specified in this package? The primary reason I ask is that I was gonna publish `eslint-config-pretty-standard` to match my cli tool (based on standard-engine), but then realised the name is taken. I think the projects are trying to achieve the same thing, so maybe there's a way to collaborate here?

**Comment by sunesimonsen** [comment]
@KidkArolis sorry that I never got back to you on this issue. I guess you have moved on to better things 😄 I probably need to rethink this package as it is just something I made to fix a problem I personally have on my projects. In https://unexpected.js.org we actually moved on to this setup https://github.com/unexpectedjs/unexpected/blob/master/.eslintrc maybe pickybacking on these other packages is a good idea and just have this package collect the configuration so you don't need to setup it up every time.

**Comment by KidkArolis** [comment]
Oh yeah, no worries, I've since built a tool called [healthier](https://github.com/KidkArolis/healthier) and a sharable config [eslint-config-healthier](https://github.com/KidkArolis/eslint-config-healthier).

The `eslint-config-healthier` is pretty much equivalent of you doing `"standard", "prettier", "prettier/standard"` in unexpected, but avoids you having to install "eslint-config-prettier", "eslint-config-standard", "eslint-plugin-import", "eslint-plugin-markdown", "eslint-plugin-mocha", "eslint-plugin-node", "eslint-plugin-promise", "eslint-plugin-standard". I personally find that valuable, but whatever works!

Thanks for getting back to me.

**Comment by sunesimonsen** [comment]
That does sound a lot healthier - I'll check it out.
